name: Ask Question
description: Ask a question for further understanding.
labels: ['question']

body:
- type: markdown
  attributes:
    value: >
      #### â˜ Please ensure that your question is about the repo.
- type: textarea
  attributes:
    label: What is your question?
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
    placeholder: > 
      If applicable, add more contexts (e.g., screenshots) to help describe your question.
