name: Sync requirements.txt with pyproject.toml

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.env/pyproject.toml'
  workflow_dispatch:

jobs:
  sync-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install toml and packaging
        run: |
          pip install toml packaging

      - name: Ensure scripts directory exists
        run: |
          mkdir -p .github/scripts

      - name: Sync requirements.txt with pyproject.toml
        run: |
          python .github/scripts/sync_requirements.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(deps): Sync `requirements.txt` with pyproject.toml [auto]'
          file_pattern: '.env/requirements.txt'
